
#opt <- list(samplesFile="samples.txt",readsFolder="02-Cleaned",NewblerFolder="05-Assemblies")
opt <- list(samplesFile="samples.txt",readsFolder="04-extra-human-extracted",NewblerFolder="05-NewblerAssemblies")

newbler_header <- function(output){
  config_output <- c(
    "#!/bin/sh",
    "## Script autogenerated by configure_Newbler.R")
  writeLines(config_output,output)
}

write_out_newbler_assembly <- function(reads,vector="vector/pCC2FOS_cloning_vector.fasta",folder,sample,script,cpus=1){
  reads <- paste(reads,collapse=" ")
  call <- "runAssembly"
#  params <- paste("-force -noace -cpu",cpus,"-m -sio -rip -urt",sep=" ")
  params <- paste("-force -noace -cpu",cpus,"-m -sio",sep=" ")
  output <- paste("-o",file.path(getwd(),folder,sample),sep=" ")
#  vector <- paste("-vt", file.path(getwd(),vector),sep=" ")
#  fullCall <- paste("nohup",call,params,vector,output,reads,"&",sep=" ")
  fullCall <- paste("nohup",call,params,output,reads,"&",sep=" ")
  writeLines(fullCall,script)
}

dir.create(opt$NewblerFolder,showWarnings=FALSE,recursive=TRUE)

if(!file.exists(dir(pattern=opt$samplesFile,full.names=TRUE))) stop("Samples file does not exist")
samples <- read.table(opt$samplesFile,sep="",header=T,as.is=T)

zz <- file(file.path(opt$NewblerFolder,"runNewbler.sh"), "w")  # open an output file connection
newbler_header(zz)

for (i in unique(samples$SAMPLE_ID)){
  read2assemble <- dir(file.path(getwd(),opt$readsFolder,i),pattern="fastq|sff",full.names=TRUE)  
  write_out_newbler_assembly(reads=read2assemble,folder=opt$NewblerFolder,sample=i,script=zz)         
}
close(zz)

Sys.chmod(file.path(opt$NewblerFolder,"runNewbler.sh"),"775")
